# Generated by Django 3.1.5 on 2021-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210112_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='listPosition',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
