# Generated by Django 3.1.5 on 2021-01-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_listposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='listPosition',
        ),
    ]
