# Generated by Django 3.1.5 on 2021-01-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_exercise_listposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
