export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

export const UPDATE_WORKOUT = 'UPDATE_WORKOUT';
export const DISCARD_CHANGES = 'DISCARD_CHANGES';

export const INITIALISE_WORKOUTS_FROM_FIREBASE = 'INITIALISE_WORKOUTS_FROM_FIREBASE';
export const CLEAR_WORKOUTS = 'CLEAR_WORKOUTS';

export const SAVE_REQUIRED = 'SAVE_REQUIRED';

export const SET_WORKSPACE_STATE = 'SET_WORKSPACE_STATE';
export const SET_WORKSPACE_WORKOUT = 'SET_WORKSPACE_WORKOUT';
export const SET_SELECTED_EXERCISE = 'SET_SELECTED_EXERCISE';

export const SWITCH_EXERCISES = 'SWITCH_EXERCISES';


export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
